# Generated by Django 5.1.7 on 2025-05-26 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0024_alter_costes_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 26)),
        ),
    ]
